// Generated by https://quicktype.io

export interface Stats {
    avatar:               string;
    country:              string;
    cover_featured_image: string;
    cover_image:          string;
    faceit_url:           string;
    friends_ids:          string[];
    games:                Games;
    membership_type:      string;
    memberships:          string[];
    new_steam_id:         string;
    nickname:             string;
    platforms:            Platforms;
    player_id:            string;
    settings:             Settings;
    steam_id_64:          string;
    steam_nickname:       string;
}

export interface Games {
    additionalProp1: AdditionalProp;
    additionalProp2: AdditionalProp;
    additionalProp3: AdditionalProp;
}

export interface AdditionalProp {
    faceit_elo:        number;
    game_player_id:    string;
    game_player_name:  string;
    game_profile_id:   string;
    region:            string;
    skill_level:       number;
    skill_level_label: string;
}

export interface Platforms {
    additionalProp1: string;
    additionalProp2: string;
    additionalProp3: string;
}

export interface Settings {
    language: string;
}
